name: services
description: grpc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  grpc: ^3.0.0
  fixnum: ^1.0.0
  protobuf: ^2.0.0
  http2: ^2.0.0
  meta: ^1.2.4
  pem: ^1.0.1
  logger:
    path: ../logger

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
