name: services
description: grpc

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.0.0
  fixnum: ^1.0.0
  protobuf: ^3.0.0
  http2: ^2.0.0
  meta: ^1.2.4
  pem: ^2.0.0
  logger:
    path: ../logger

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
