name: logger
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.1
  #路径信息获取        https://github.com/flutter/plugins

  isolate: ^2.0.3

  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
