name: client_dart
description: Dart gRPC sample client and server.
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  async: ^2.2.0
  grpc: ^3.0.0
  protobuf: ^2.0.0
