name: flutter_test_demo
description: A new Flutter application that use to test some feature

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  path_provider: ^1.3.0

  json_annotation: ^3.1.0

  provider: ^3.1.0
  # 状态管理           https://github.com/rrousselGit/provider

  dio:  ^3.0.9
  # 网络请求           https://github.com/flutterchina/dio

  fluttertoast: ^7.1.1
  #                    https://github.com/PonnamKarthik/FlutterToast

  oktoast: ^2.2.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast

  fluro: "^1.7.2"
  # 路由管理           https://github.com/theyakka/fluro

  flutter_webview_plugin: ^0.3.11

  webview_flutter: ^0.3.20+2

  device_info: ^0.4.2+4
  # 获取设备id

  qr_flutter: ^3.0.1
  # 生成二维码         https://github.com/lukef/qr.flutter

  flutter_swiper: ^1.1.6
  #                    https://github.com/jzoom/flutter_swiper

  flutter_screenutil: ^3.1.1
  # 屏幕适配           https://github.com/OpenFlutter/flutter_screenutil

  flutter_easyrefresh: ^2.0.3
  # 上下拉刷新功能     https://github.com/xuelongqy/flutter_easyrefresh

  web_socket_channel: ^1.1.0
  # 通过socket通信     https://pub.dev/packages/web_socket_channel#-installing-tab-

  stream_channel: ">=1.1.0 <3.0.0"

  flutter_html: ^0.10.4
  #flutter_html: ^1.0.2
  #                    https://github.com/Sub6Resources/flutter_html

  shared_preferences: ^0.5.7+1
  #https://github.com/flutter/plugins

  package_info: ^0.4.0+18
  #yingyongbanben

  permission_handler: ^5.0.1+1
  # https://github.com/Baseflow/flutter-permission-handler

  json_rpc_2: ^2.1.1
  #         https://github.com/dart-lang/json_rpc_2

  grpc: ^2.3.0
  # https://github.com/grpc/grpc-dart

  sqflite: ^1.3.0
  # https://github.com/tekartik/sqflite

  flutter_page_tracker: ^1.2.2

  google_fonts: ^1.1.1
  # https://github.com/material-foundation/google-fonts-flutter

  ffi: ^1.0.0

  wallets:
    path: ../../packages/wallets

  logger:
    path: ../../packages/logger

  services:
    path: ../../packages/services

  async: ^2.2.0

  protobuf: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^3.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/config/config.json