[package]
name = "scry-crypto"
version = "0.1.0"
authors = ["jeremy <jm140915@hotmail.com>"]
edition = "2018"

[dependencies]
hex = { version = "0.4" }
ring = "0.16.9"
rand = "0.8.5"
tiny-keccak = { version = "2.0", features = ["keccak"] }
rust-crypto = "0.2"
