name: app
description: Wallet Cashbox
version: 2.3.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^4.0.4
  cupertino_icons: ^1.0.0
  provider: ^6.0.5
  dio: ^5.2.1+1
  fluttertoast: ^8.2.2
  fluro: ^2.0.5
  webview_flutter: ^4.2.2

  flutter_html: ^3.0.0-beta.2
  device_info_plus: ^9.0.2
  platform_device_id: ^1.0.1
  package_info_plus: ^4.0.2
  progress_loading_button: ^2.0.2
  sn_progress_dialog: ^1.0.2
  cached_network_image: ^3.2.3
  rflutter_alert: ^2.0.2
  qr_flutter: ^4.1.0
  flutter_swiper_view: ^1.1.8
  flutter_screenutil: ^5.8.4
  flutter_easyrefresh: ^2.0.3
  web_socket_channel: ^2.4.0
  stream_channel: ^2.1.1
  path_provider: ^2.0.1
  permission_handler: ^10.3.0
  json_rpc_2: ^3.0.2
  grpc: ^3.2.2
  google_fonts:
  material_dialogs: ^1.0.0
  ffi: ^2.0.2
  json_annotation: ^4.8.1
  shared_preferences: ^2.1.2
  uuid: ^3.0.7
  wallets:
    path: ../packages/wallets
  logger:
    path: ../packages/logger
  services:
    path: ../packages/services
  webviews:
    path: ../packages/webviews
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/i18n/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

