name: gen_dl
description: A new source gen package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.0.0
  source_gen: ^1.0.0
  ffi: ^1.0.0

dev_dependencies:
  build: ^2.0.0
  build_test: ^2.0.0
  test: ^1.16.8