name: gen_dl
description: A new source gen package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  analyzer: ^5.13.0
  source_gen: ^1.0.0
  ffi: ^2.0.2

dev_dependencies:
  build: ^2.0.0
  build_test: ^2.0.0
  test: ^1.16.8