name: wallets
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.2
  path: ^1.8.0
  logger:
    path: ../logger

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^8.0.2
  build_runner: ^2.4.5
  gen_dl:
    path: ../gen_dl
  logger:
    path: ../logger

flutter:

ffigen:
  name: 'CWallets'
  output: 'lib/wallets_c.dart'
  headers:
    entry-points:
      - '../../bc/wallets_cdl/src/wallets_c.h'
#  llvm-path:
#    - 'd:/lang/LLVM/bin'
#  compiler-opts:
#    - '-Id:/lang/LLVM/include -Ld:/lang/LLVM/lib'
#  compiler-opts-automatic:
#    macos:
#      include-c-standard-library: false
#  typedef-map:
#    'bool': 'Uint32'
