name: wallets
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.0.0
  path: ^1.8.0
  logger:
    path: ../logger

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^2.4.0
  build_runner: ^1.10.3
  gen_dl:
    path: ../gen_dl
  logger:
    path: ../logger

flutter:

ffigen:
  name: 'CWallets'
  output: 'lib/wallets_c.dart'
  headers:
    entry-points:
      - '../../bc/wallets_cdl/src/wallets_c.h'
#  llvm-path: 'd:/lang/LLVM/bin'
#  typedef-map:
#    'bool': 'Uint32'
